# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(603, 500)
        MainWindow.setMinimumSize(QtCore.QSize(603, 500))
        MainWindow.setMaximumSize(QtCore.QSize(603, 500))
        font = QtGui.QFont()
        font.setPointSize(10)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.centralwidget.setFont(font)
        self.centralwidget.setObjectName("centralwidget")
        self.pixel_frame = QtWidgets.QFrame(self.centralwidget)
        self.pixel_frame.setGeometry(QtCore.QRect(10, 10, 321, 411))
        self.pixel_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.pixel_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.pixel_frame.setObjectName("pixel_frame")
        self.gridLayout = QtWidgets.QGridLayout(self.pixel_frame)
        self.gridLayout.setObjectName("gridLayout")
        self.pixel6 = QtWidgets.QPushButton(self.pixel_frame)
        self.pixel6.setText("")
        self.pixel6.setCheckable(True)
        self.pixel6.setObjectName("pixel6")
        self.gridLayout.addWidget(self.pixel6, 1, 0, 1, 1)
        self.pixel2 = QtWidgets.QPushButton(self.pixel_frame)
        self.pixel2.setText("")
        self.pixel2.setCheckable(True)
        self.pixel2.setObjectName("pixel2")
        self.gridLayout.addWidget(self.pixel2, 0, 1, 1, 1)
        self.pixel32 = QtWidgets.QPushButton(self.pixel_frame)
        self.pixel32.setText("")
        self.pixel32.setCheckable(True)
        self.pixel32.setObjectName("pixel32")
        self.gridLayout.addWidget(self.pixel32, 17, 1, 1, 1)
        self.pixel1 = QtWidgets.QPushButton(self.pixel_frame)
        self.pixel1.setText("")
        self.pixel1.setCheckable(True)
        self.pixel1.setChecked(False)
        self.pixel1.setObjectName("pixel1")
        self.gridLayout.addWidget(self.pixel1, 0, 0, 1, 1)
        self.pixel4 = QtWidgets.QPushButton(self.pixel_frame)
        self.pixel4.setText("")
        self.pixel4.setCheckable(True)
        self.pixel4.setObjectName("pixel4")
        self.gridLayout.addWidget(self.pixel4, 0, 3, 1, 1)
        self.pixel38 = QtWidgets.QPushButton(self.pixel_frame)
        self.pixel38.setText("")
        self.pixel38.setCheckable(True)
        self.pixel38.setObjectName("pixel38")
        self.gridLayout.addWidget(self.pixel38, 18, 2, 1, 1)
        self.pixel34 = QtWidgets.QPushButton(self.pixel_frame)
        self.pixel34.setText("")
        self.pixel34.setCheckable(True)
        self.pixel34.setObjectName("pixel34")
        self.gridLayout.addWidget(self.pixel34, 17, 3, 1, 1)
        self.pixel33 = QtWidgets.QPushButton(self.pixel_frame)
        self.pixel33.setText("")
        self.pixel33.setCheckable(True)
        self.pixel33.setObjectName("pixel33")
        self.gridLayout.addWidget(self.pixel33, 17, 2, 1, 1)
        self.pixel24 = QtWidgets.QPushButton(self.pixel_frame)
        self.pixel24.setText("")
        self.pixel24.setCheckable(True)
        self.pixel24.setObjectName("pixel24")
        self.gridLayout.addWidget(self.pixel24, 8, 3, 1, 1)
        self.pixel18 = QtWidgets.QPushButton(self.pixel_frame)
        self.pixel18.setText("")
        self.pixel18.setCheckable(True)
        self.pixel18.setObjectName("pixel18")
        self.gridLayout.addWidget(self.pixel18, 4, 2, 1, 1)
        self.pixel36 = QtWidgets.QPushButton(self.pixel_frame)
        self.pixel36.setText("")
        self.pixel36.setCheckable(True)
        self.pixel36.setObjectName("pixel36")
        self.gridLayout.addWidget(self.pixel36, 18, 0, 1, 1)
        self.pixel16 = QtWidgets.QPushButton(self.pixel_frame)
        self.pixel16.setText("")
        self.pixel16.setCheckable(True)
        self.pixel16.setObjectName("pixel16")
        self.gridLayout.addWidget(self.pixel16, 4, 0, 1, 1)
        self.pixel27 = QtWidgets.QPushButton(self.pixel_frame)
        self.pixel27.setText("")
        self.pixel27.setCheckable(True)
        self.pixel27.setObjectName("pixel27")
        self.gridLayout.addWidget(self.pixel27, 13, 1, 1, 1)
        self.pixel26 = QtWidgets.QPushButton(self.pixel_frame)
        self.pixel26.setText("")
        self.pixel26.setCheckable(True)
        self.pixel26.setObjectName("pixel26")
        self.gridLayout.addWidget(self.pixel26, 13, 0, 1, 1)
        self.pixel28 = QtWidgets.QPushButton(self.pixel_frame)
        self.pixel28.setText("")
        self.pixel28.setCheckable(True)
        self.pixel28.setObjectName("pixel28")
        self.gridLayout.addWidget(self.pixel28, 13, 2, 1, 1)
        self.pixel29 = QtWidgets.QPushButton(self.pixel_frame)
        self.pixel29.setText("")
        self.pixel29.setCheckable(True)
        self.pixel29.setObjectName("pixel29")
        self.gridLayout.addWidget(self.pixel29, 13, 3, 1, 1)
        self.pixel8 = QtWidgets.QPushButton(self.pixel_frame)
        self.pixel8.setText("")
        self.pixel8.setCheckable(True)
        self.pixel8.setObjectName("pixel8")
        self.gridLayout.addWidget(self.pixel8, 1, 2, 1, 1)
        self.pixel7 = QtWidgets.QPushButton(self.pixel_frame)
        self.pixel7.setText("")
        self.pixel7.setCheckable(True)
        self.pixel7.setObjectName("pixel7")
        self.gridLayout.addWidget(self.pixel7, 1, 1, 1, 1)
        self.pixel14 = QtWidgets.QPushButton(self.pixel_frame)
        self.pixel14.setText("")
        self.pixel14.setCheckable(True)
        self.pixel14.setObjectName("pixel14")
        self.gridLayout.addWidget(self.pixel14, 2, 3, 1, 1)
        self.pixel9 = QtWidgets.QPushButton(self.pixel_frame)
        self.pixel9.setText("")
        self.pixel9.setCheckable(True)
        self.pixel9.setObjectName("pixel9")
        self.gridLayout.addWidget(self.pixel9, 1, 3, 1, 1)
        self.pixel35 = QtWidgets.QPushButton(self.pixel_frame)
        self.pixel35.setText("")
        self.pixel35.setCheckable(True)
        self.pixel35.setObjectName("pixel35")
        self.gridLayout.addWidget(self.pixel35, 17, 4, 1, 1)
        self.pixel12 = QtWidgets.QPushButton(self.pixel_frame)
        self.pixel12.setText("")
        self.pixel12.setCheckable(True)
        self.pixel12.setObjectName("pixel12")
        self.gridLayout.addWidget(self.pixel12, 2, 1, 1, 1)
        self.pixel10 = QtWidgets.QPushButton(self.pixel_frame)
        self.pixel10.setText("")
        self.pixel10.setCheckable(True)
        self.pixel10.setObjectName("pixel10")
        self.gridLayout.addWidget(self.pixel10, 1, 4, 1, 1)
        self.pixel40 = QtWidgets.QPushButton(self.pixel_frame)
        self.pixel40.setText("")
        self.pixel40.setCheckable(True)
        self.pixel40.setObjectName("pixel40")
        self.gridLayout.addWidget(self.pixel40, 18, 4, 1, 1)
        self.pixel39 = QtWidgets.QPushButton(self.pixel_frame)
        self.pixel39.setText("")
        self.pixel39.setCheckable(True)
        self.pixel39.setObjectName("pixel39")
        self.gridLayout.addWidget(self.pixel39, 18, 3, 1, 1)
        self.pixel37 = QtWidgets.QPushButton(self.pixel_frame)
        self.pixel37.setText("")
        self.pixel37.setCheckable(True)
        self.pixel37.setObjectName("pixel37")
        self.gridLayout.addWidget(self.pixel37, 18, 1, 1, 1)
        self.pixel15 = QtWidgets.QPushButton(self.pixel_frame)
        self.pixel15.setText("")
        self.pixel15.setCheckable(True)
        self.pixel15.setObjectName("pixel15")
        self.gridLayout.addWidget(self.pixel15, 2, 4, 1, 1)
        self.pixel17 = QtWidgets.QPushButton(self.pixel_frame)
        self.pixel17.setText("")
        self.pixel17.setCheckable(True)
        self.pixel17.setObjectName("pixel17")
        self.gridLayout.addWidget(self.pixel17, 4, 1, 1, 1)
        self.pixel31 = QtWidgets.QPushButton(self.pixel_frame)
        self.pixel31.setText("")
        self.pixel31.setCheckable(True)
        self.pixel31.setObjectName("pixel31")
        self.gridLayout.addWidget(self.pixel31, 17, 0, 1, 1)
        self.pixel13 = QtWidgets.QPushButton(self.pixel_frame)
        self.pixel13.setText("")
        self.pixel13.setCheckable(True)
        self.pixel13.setObjectName("pixel13")
        self.gridLayout.addWidget(self.pixel13, 2, 2, 1, 1)
        self.pixel3 = QtWidgets.QPushButton(self.pixel_frame)
        self.pixel3.setText("")
        self.pixel3.setCheckable(True)
        self.pixel3.setObjectName("pixel3")
        self.gridLayout.addWidget(self.pixel3, 0, 2, 1, 1)
        self.pixel25 = QtWidgets.QPushButton(self.pixel_frame)
        self.pixel25.setText("")
        self.pixel25.setCheckable(True)
        self.pixel25.setObjectName("pixel25")
        self.gridLayout.addWidget(self.pixel25, 8, 4, 1, 1)
        self.pixel22 = QtWidgets.QPushButton(self.pixel_frame)
        self.pixel22.setText("")
        self.pixel22.setCheckable(True)
        self.pixel22.setObjectName("pixel22")
        self.gridLayout.addWidget(self.pixel22, 8, 1, 1, 1)
        self.pixel11 = QtWidgets.QPushButton(self.pixel_frame)
        self.pixel11.setText("")
        self.pixel11.setCheckable(True)
        self.pixel11.setObjectName("pixel11")
        self.gridLayout.addWidget(self.pixel11, 2, 0, 1, 1)
        self.pixel19 = QtWidgets.QPushButton(self.pixel_frame)
        self.pixel19.setText("")
        self.pixel19.setCheckable(True)
        self.pixel19.setObjectName("pixel19")
        self.gridLayout.addWidget(self.pixel19, 4, 3, 1, 1)
        self.pixel30 = QtWidgets.QPushButton(self.pixel_frame)
        self.pixel30.setText("")
        self.pixel30.setCheckable(True)
        self.pixel30.setObjectName("pixel30")
        self.gridLayout.addWidget(self.pixel30, 13, 4, 1, 1)
        self.pixel20 = QtWidgets.QPushButton(self.pixel_frame)
        self.pixel20.setText("")
        self.pixel20.setCheckable(True)
        self.pixel20.setObjectName("pixel20")
        self.gridLayout.addWidget(self.pixel20, 4, 4, 1, 1)
        self.pixel21 = QtWidgets.QPushButton(self.pixel_frame)
        self.pixel21.setText("")
        self.pixel21.setCheckable(True)
        self.pixel21.setObjectName("pixel21")
        self.gridLayout.addWidget(self.pixel21, 8, 0, 1, 1)
        self.pixel5 = QtWidgets.QPushButton(self.pixel_frame)
        self.pixel5.setText("")
        self.pixel5.setCheckable(True)
        self.pixel5.setObjectName("pixel5")
        self.gridLayout.addWidget(self.pixel5, 0, 4, 1, 1)
        self.pixel23 = QtWidgets.QPushButton(self.pixel_frame)
        self.pixel23.setText("")
        self.pixel23.setCheckable(True)
        self.pixel23.setObjectName("pixel23")
        self.gridLayout.addWidget(self.pixel23, 8, 2, 1, 1)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(10, 430, 581, 44))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.learn_button = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.learn_button.setObjectName("learn_button")
        self.horizontalLayout_2.addWidget(self.learn_button)
        self.test_button = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.test_button.setObjectName("test_button")
        self.horizontalLayout_2.addWidget(self.test_button)
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(350, 10, 221, 411))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.class_name = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.class_name.setObjectName("class_name")
        self.horizontalLayout.addWidget(self.class_name)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.done_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.done_button.setObjectName("done_button")
        self.verticalLayout.addWidget(self.done_button)
        self.clear_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.clear_button.setObjectName("clear_button")
        self.verticalLayout.addWidget(self.clear_button)
        self.output = QtWidgets.QPlainTextEdit(self.verticalLayoutWidget)
        self.output.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.output.setFont(font)
        self.output.setReadOnly(True)
        self.output.setObjectName("output")
        self.verticalLayout.addWidget(self.output)
        self.save_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.save_button.setObjectName("save_button")
        self.verticalLayout.addWidget(self.save_button)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "SimpleNumberRecognizer"))
        self.learn_button.setText(_translate("MainWindow", "Learn"))
        self.test_button.setText(_translate("MainWindow", "Test"))
        self.label.setText(_translate("MainWindow", "Class name:"))
        self.done_button.setText(_translate("MainWindow", "Done"))
        self.clear_button.setText(_translate("MainWindow", "Clear"))
        self.save_button.setText(_translate("MainWindow", "Save file"))

